# Linear Algebra

## Addition and Subtraction

For matrix addition and subtraction, you need two of the exact same sized matricies. For example, A = 2columns x 2rows and B = 2columns x 2rows. To add them, you add the corresponding elements to get a matrix of the same size.

In [1]:
import numpy as np

A = np.array([[2, 3],
              [4, 5]])

B = np.array([[1, 0],
              [2, 8]])

A + B

array([[ 3,  3],
       [ 6, 13]])

In [2]:
A - B

array([[ 1,  3],
       [ 2, -3]])

# Multiplication

Multiplying matricies is a bit more complicated. Unlike multiplying numbers, there is no commutative property. The order you multiply matricies is important. The number of rows in the first matrix must match the number of columns in the second matrix. The matrix you recieve is the amount of columns of the first matrix by the amount of rows in the second matrix. For example, multiplying a (2x4) and (4x3) matrix will produce a (2x3) matrix.

To actually do the multiplication, you multiply each element of the first row in the first matrix by each element of the first column of the second matrix. You add these values and the result becomes the first element in the resulting matrix. You follow this pattern until the whole resulting matrix is filled.

In [4]:
A = np.array([[2, 3, 4],
              [9, 4, 2]])

B = np.array([[2, 3],
              [8, 9],
              [0, 1]])

A @ B

array([[28, 37],
       [50, 65]])

# Determinant

The determinant is a characteristic of a matrix that can provide different information about the matrix. Most notably, it tells us if there is an inverse of the matrix. If the determinant is 0, there is no inverse. To calculate the determinant of matrix A =  [[a,b][c,d]], you use the following formula, det(A) = ad-bc. 

In [10]:
A = np.array([[0.75, 0, 0],
              [-0.5, 0.75, 0],
              [-0.25, -0.5, 0.75]])

detA = np.linalg.det(A)
detA

0.42187500000000006

## Inverse

The inverse of a matrix is what you multiply to get the identity matrix. It is equivaled to division for numbers. To find the inverse, scale the adjugate matrix, A, by 1/det(A).

In [11]:
np.linalg.inv(A)

array([[1.33333333, 0.        , 0.        ],
       [0.88888889, 1.33333333, 0.        ],
       [1.03703704, 0.88888889, 1.33333333]])

In [15]:
np.linalg.adjugate(A)

AttributeError: module 'numpy.linalg' has no attribute 'adjugate'

In [13]:
(1/detA) * np.adju

array([[ 1.77777778,  0.        ,  0.        ],
       [-1.18518519,  1.77777778,  0.        ],
       [-0.59259259, -1.18518519,  1.77777778]])

## Row Reduction for linear systems

In [48]:
from sympy import Matrix
A = Matrix([
            [4, 4, 1, 2500],
            [1, 2, 0, 600],
            [0, 0, 258.8011, 258.8011]
                ])

A.rref()

(Matrix([
 [1, 0, 0,  649.5],
 [0, 1, 0, -24.75],
 [0, 0, 1,    1.0]]),
 (0, 1, 2))

In [38]:
t1 = np.arctan(40/30) * 180 / np.pi
t2 = np.arctan(10/20) * 180 / np.pi
t3 = (180 - 90 - t1 - t2) * np.pi / 180

In [39]:
t3

0.17985349979247822

In [43]:
(np.sqrt(500) / np.arccos(t3))**2

258.8011164379651